tm_event_game_rest:
    type: rest
    resource: "TeamManagerEventBundle:GameRest"
    name_prefix: api_game_
    prefix:   game

tm_event_gamefriendly_rest:
    type: rest
    resource: "TeamManagerEventBundle:GameFriendlyRest"
    name_prefix: api_game_friendly_
    prefix:   gamefriendly

tm_event_training_rest:
    type: rest
    resource: "TeamManagerEventBundle:TrainingRest"
    name_prefix: api_training_
    prefix:   training