tm_result_comment_rest:
    type: rest
    resource: "TeamManagerResultBundle:CommentRest"
    name_prefix: api_comment_
    prefix: comment

tm_result_note_rest:
    type: rest
    resource: "TeamManagerResultBundle:NoteRest"
    name_prefix: api_note_
    prefix: note