<?php

namespace TeamManager\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameFriendlyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameFriendlyRepository extends EntityRepository
{
}
