<?php

namespace TeamManager\ActionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InjuryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InjuryRepository extends EntityRepository
{
}
