team_manager_security:
    resource: "@TeamManagerSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

team_manager_action:
    resource: "@TeamManagerActionBundle/Controller/"
    type:     annotation
    prefix:   /

team_manager_result:
    resource: "@TeamManagerResultBundle/Controller/"
    type:     annotation
    prefix:   /

team_manager_event:
    resource: "@TeamManagerEventBundle/Controller/"
    type:     annotation
    prefix:   /

team_manager_player:
    resource: "@TeamManagerPlayerBundle/Controller/"
    type:     annotation
    prefix:   /

team_manager_team:
    resource: "@TeamManagerTeamBundle/Controller/"
    type:     annotation
    prefix:   /

tm_result:
    resource: "@TeamManagerResultBundle/Controller/"
    type:     annotation
    prefix:   /

tm_player:
    resource: "@TeamManagerPlayerBundle/Controller/"
    type:     annotation
    prefix:   /

tm_team:
    resource: "@TeamManagerTeamBundle/Controller/"
    type:     annotation
    prefix:   /

tm_event:
    resource: "@TeamManagerEventBundle/Controller/"
    type:     annotation
    prefix:   /
