fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

tm_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: TeamManagerSecurityBundle:Security:login }

tm_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: TeamManagerSecurityBundle:Security:loginCheck }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/docs

tm_action:
    resource: "@TeamManagerActionBundle/Resources/config/routing_rest.yml"
    type:     rest
    prefix:   /api/action/

tm_result:
    resource: "@TeamManagerResultBundle/Resources/config/routing_rest.yml"
    type:     rest
    prefix:   /api/result/

tm_event:
    resource: "@TeamManagerEventBundle/Resources/config/routing_rest.yml"
    type:     rest
    prefix:   /api/

tm_player:
    resource: "@TeamManagerPlayerBundle/Resources/config/routing_rest.yml"
    type:     rest
    prefix:   /api/player/

tm_team:
    resource: "@TeamManagerTeamBundle/Resources/config/routing_rest.yml"
    type:     rest
    prefix:   /api/team/