<?php

namespace TeamManager\PlayerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{

    /**
     * @param $id
     */
    public function findOneById($id, $fullObject=true)
    {
        $query = $this->createQueryBuilder('player');
        $query->where('player.id = :playerID')
            ->setParameter('playerID', $id)
        ;

        if($fullObject){
            //?
        }
        $result = $query->getQuery()->getResult();
        if(isset($result[0])){
            return $result[0];
        }
        return $query->getQuery()->getResult();
    }

    /**
     * Returns all trainings of a given player.
     *
     * @param $pPlayerID
     */
    public function getPlayerTrainings($pPlayerID)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('training')
            ->from('TeamManagerEventBundle:Training', 'training')
            ->innerjoin('training.team', 'team', 'WITH', 'team = training.team')
            ->innerjoin('team.players', 'player', 'WITH', $query->expr()->eq('player.id', $pPlayerID))
        ;

        return $query->getQuery()->getResult();
    }

}
