tm_action_card_rest:
    type: rest
    resource: "TeamManagerActionBundle:CardRest"
    name_prefix: api_card

tm_action_goal_rest:
    type: rest
    resource: "TeamManagerActionBundle:GoalRest"
    name_prefix: api_goal

tm_action_injury_rest:
    type: rest
    resource: "TeamManagerActionBundle:InjuryRest"
    name_prefix: api_injury

tm_action_playtime_rest:
    type: rest
    resource: "TeamManagerActionBundle:PlayTimeRest"
    name_prefix: api_playtime