<?php

namespace TeamManager\TeamBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{

    /**
     * @param $id
     */
    public function findAll()
    {
        $query = $this->createQueryBuilder('team');
        $query->join('team.default_location', 'location')
            ->addSelect('location')
            ->join('team.manager', 'manager')
            ->addSelect('manager');
        return $query->getQuery()->getResult();
    }

    /**
     * @param $id
     */
    public function findOneById($id)
    {
        $query = $this->createQueryBuilder('team');
        $query->join('team.default_location', 'location')
            ->addSelect('location')
            ->join('team.manager', 'manager')
            ->addSelect('manager')
            ->where('team.id = :teamID')
            ->setParameter('teamID', $id)
        ;
        $result = $query->getQuery()->getResult();
        if(isset($result[0])){
            return $result[0];
        }
        return $query->getQuery()->getResult();
    }

}
