<?php

namespace TeamManager\ResultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerResultRepository extends EntityRepository
{
}
