<?php

namespace TeamManager\ResultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamResultRepository extends EntityRepository
{
}
